-- DDL (DATA DEFINITION LANGUAGE)

-- CREATE TABLE
CREATE TABLE IF NOT EXISTS CAR(ID SERIAL PRIMARY KEY, NAME TEXT);

-- ALTER TABLE
ALTER TABLE CAR ADD COLUMN COLOR TEXT;

-- DROP TABLE
DROP TABLE CAR;

-- DML (DATA MANIPULATION LAUNGUAGE)

--SELECT * FROM CAR;

-- INSERT A ROW
INSERT INTO CAR(id, name) VALUES(1, 'Maruti Suzuki');
INSERT INTO CAR(id, name) VALUES(2, 'Maruti Swift');
INSERT INTO CAR(id, name) VALUES(3, 'Maruti Baleno');
INSERT INTO CAR(ID, NAME) VALUES(4, 'Mahindra Bolero');

-- GETTING ALL ROWS
SELECT * FROM CAR;

-- GET A SPECIFIC ROW
SELECT * FROM CAR WHERE ID=3;


-- UPDATE A ROW
UPDATE CAR SET NAME='Maruti Alto' WHERE ID=1;
UPDATE CAR SET NAME='Maruti Swift' WHERE ID=1 OR ID=4;
UPDATE CAR SET NAME='Maruti Swift' WHERE ID IN (1,3);
UPDATE CAR SET NAME='Maruti Swift' WHERE ID NOT IN (2,4);


-- UPDATE ALL ROWS
UPDATE CAR SET NAME='Maruti Alto';


-- DELETE A ROW
DELETE FROM CAR WHERE ID=4;

DELETE FROM CAR;

-- SQL BUILT IN OPERATORS
SELECT * FROM CAR WHERE ID IN (1,4);
SELECT * FROM CAR WHERE ID >= 1 AND ID <= 3;
SELECT * FROM CAR WHERE ID BETWEEN 1 AND 3;
SELECT * FROM CAR WHERE NAME LIKE 'Maruti Swift';
SELECT * FROM CAR WHERE NAME LIKE 'Maruti%';
SELECT * FROM CAR WHERE NAME LIKE '%Swift';
SELECT * FROM CAR WHERE NAME LIKE '%Al%';
SELECT * FROM CAR WHERE NAME LIKE '%Swift' AND ID BETWEEN 1 AND 3;

-- SORTING
SELECT * FROM CAR ORDER BY ID;
SELECT * FROM CAR ORDER BY ID DESC;
SELECT * FROM CAR WHERE NAME LIKE '%Swift' AND ID BETWEEN 1 AND 3 ORDER BY ID DESC;

-- TRUNCATE
TRUNCATE CAR;








